apiVersion: v1
kind: Service
metadata:
  name: laravel-loadbalancer
spec:
  type: LoadBalancer    # Use NodePort if LoadBalancer unavailable
  selector:
    app: laravel        # Match your pod label
  ports:
    - name: http
      protocol: TCP
      port: 8090         # External port
      targetPort: 8080   # Web server container port
    - name: mysql
      protocol: TCP
      port: 3306         # External port for MySQL
      targetPort: 3306   # MySQL container port
    - name: ssh
      protocol: TCP
      port: 22           # External port for SSH
      targetPort: 22     # Web server SSH port

