apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort   # or LoadBalancer if on cloud
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30881  # Custom NodePort
